// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iBOS.Models;

#nullable disable

namespace iBOS.Migrations
{
    [DbContext(typeof(iBOSContext))]
    [Migration("20230606212302_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("iBOS.Models.tblEmployee", b =>
                {
                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("employeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("employeeSalary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("employeeId");

                    b.ToTable("tblEmployees");
                });

            modelBuilder.Entity("iBOS.Models.tblEmployeeAttendance", b =>
                {
                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("attendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isAbsent")
                        .HasColumnType("bit");

                    b.Property<bool>("isOffday")
                        .HasColumnType("bit");

                    b.Property<bool>("isPresent")
                        .HasColumnType("bit");

                    b.HasKey("employeeId");

                    b.ToTable("tblEmployeeAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
